version: '3.8'

services:
  backend:
    image: hub4media-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
